version: '4.1'
services:
  postgres_db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data

  spring_app:
    image: springboot-api-postgres
    container_name: main-container
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    ports:
      - '8081:8080'
    depends_on:
      - postgres_db

volumes:
  postgres_db: { }

