name: Build and test

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "v*"

  pull_request:
    branches:
      - "**"
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Wait for PostgreSQL
        run: |
          while ! pg_isready -h localhost -p 5432 -U postgres; do
            sleep 1
          done

      - name: Build without Tests
        run: ./gradlew clean build -x test

      - name: Run Tests
        run: ./gradlew test --info --stacktrace
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/testdb
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: password
